version: "2"

services:
  database:
    build:
      context: ./registration-database
    image: registration-database
    environment:
      MYSQL_ROOT_PASSWORD: password
    # Expose port 3306 to host. Not for the application but
    # handy to inspect the database from the host machine.
    ports:
      - "3306:3306" 
    image: registration-database
    restart: always

  webserver:
    build: 
      context: ./registration-webserver
    image: registration-webserver
    volumes:
      - ./app/target/UserSignup:/usr/local/tomcat/webapps/UserSignup
    links:
      - database:registration-database
    ports:
      - "8080:8080" 
    image: registration-webserver
    restart: always

